#!/bin/bash
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLepTau.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLepTau.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLepTauFakes.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLepTauFakes.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLepTauFlips.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLepTauFlips.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.TriLepTau.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHTriLepTau.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_3L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.TriLepTauFakes.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHTriLepTauFakes.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_3L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt


bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLep.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLep.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog 1>log
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLepFakes.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLepFakes.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.DiLepFlips.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHDiLepFlips.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.ttWControl.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHttWControl.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_2L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.TriLep.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHTriLep.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_3L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.TriLepFakes.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHTriLepFakes.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_3L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
#bin/ttH/ttH_generic.x -config config/overall/ttH.MultiLeptons.ttZControl.config -inlist config/files/ttH_test/ttH.list -hfile hists/SingleTop.105200_1.t.LP2fb_v5.MC.mm1+j.muonMSSmeardown.WtDilepton.root -skimfile skims/ttHttZControl.root -mc -BkgdTreeName DiElectronPreTagTree  -UseTotalEvtFromFile -MCatNLO -mc -SelectTrigger TTHLep_3L -lepSFs -bTagReshape -PileUpWgt -ReCalPU -chargeMis -FakeRate -TriggerSFs -mcPromptFS  2>errorLog #1>muon_sync_0410.txt
